// Generated by Wrangler on Mon Jul 29 2024 06:41:44 GMT+0700 (Indochina Time)
// by running `wrangler types`

interface Env {
	AUTH0_ISSUER: string;
	AUTH0_AUDIENCE: string;
	PRISMA_CLIENT_FORCE_WASM: string;
	AUTH0_NAMESPACE: string;
	ENVIRONMENT: string;
	AUTH0_CLIENT_ID: string;
	DB: D1Database;
}
