// Generated by Wrangler on Wed Aug 21 2024 21:52:57 GMT+0700 (Indochina Time)
// by running `wrangler types`

interface Env {
	R2PU: KVNamespace;
	AUTH0_ISSUER: string;
	AUTH0_AUDIENCE: string;
	PRISMA_CLIENT_FORCE_WASM: string;
	AUTH0_NAMESPACE: string;
	ENVIRONMENT: string;
	AUTH0_CLIENT_ID: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	BUCKET_NAME: string;
	ACCOUNT_ID: string;
	IMAGE: R2Bucket;
	DB: D1Database;
}
