// Generated by Wrangler on Tue Aug 20 2024 22:10:12 GMT+0700 (Indochina Time)
// by running `wrangler types`

interface Env {
	R2PU: KVNamespace;
	BUCKET_NAME: string;
	ACCOUNT_ID: string;
	AUTH0_ISSUER: string;
	AUTH0_AUDIENCE: string;
	PRISMA_CLIENT_FORCE_WASM: string;
	AUTH0_NAMESPACE: string;
	ENVIRONMENT: string;
	AUTH0_CLIENT_ID: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	DB: D1Database;
}
